# Generated by Django 6.0.1 on 2026-01-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., MATH2107', max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('year_level', models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Elective / Advanced')])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['year_level', 'code'],
            },
        ),
    ]
