# Generated by Django 6.0.1 on 2026-01-14 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subject_area', models.CharField(choices=[('PURE', 'Pure Mathematics'), ('APPLIED', 'Applied Mathematics'), ('STATS', 'Statistics & Probability'), ('GENERAL', 'General / Other')], max_length=20)),
                ('file', models.FileField(upload_to='textbooks/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('NOTE', 'Summary / Note'), ('EXAM', 'Past Exam'), ('SOLN', 'Solution'), ('OTHER', 'Other')], max_length=5)),
                ('file', models.FileField(upload_to='materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Approve to make visible on the site')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='academics.course')),
            ],
        ),
    ]
